[variables]
  gui = false # Default false. Override to true in ~/.config/chezmoi/chezmoi.toml on GUI machines.

[hostnames]
personal = [ "distressed-phase", "chickadee" ]
personal_remote = [ "blunderbore", "kestrel", "magpie" ]
# we keep changing names! why not add ALL the names they use?
work = [ "Shauns-MacBook-Pro", "Shauns-MacBook-Pro-2"]
