[variables]
  gui = false # Set to true on GUI machines, false on headless.

[hostnames]
personal = [ "distressed-phase" ]
personal_remote = [ "blunderbore", "kestrel", "magpie" ]
# we keep changing names! why not add ALL the names they use?
work = [ "Shauns-MacBook-Pro.local", "Mac", "Shauns-MacBook-Pro", "Shauns-MacBook-Pro-2.local"]
